const userTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  RESET_SIGN_IN_STATUS: "RESET_SIGN_IN_STATUS",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_ERROR: "SIGN_UP_ERROR",
  RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS",
  RESET_PASSWORD_ERROR: "RESET_PASSWORD_ERROR",
};

export default userTypes;
